# configuration file for dotnet-releaser
[msbuild]
project = "SubConv.sln"
[msbuild.properties]
PublishTrimmed = false
[github]
user = "kashelkin"
repo = "SubConv"
[nuget]
publish = false
[coveralls]
publish = false
